[package]
name = "codetwin-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
codetwin-core = { path = "../../../crates/codetwin-core" }
project-discovery = { path = "../../../crates/project-discovery" }
serde.workspace = true
tauri.workspace = true
