-- REGRESSION_DETECTED is the strictest (blocking) campaign outcome, yet the 0021 guard
-- let QUEUED, BLOCKED, STILL_VULNERABLE, UNABLE_TO_VERIFY and MANUAL_ACTION_REQUIRED
-- move to VERIFIED or UNABLE_TO_VERIFY but not to REGRESSION_DETECTED. Campaign sync
-- then aborted exactly when a patch-introduced regression was confirmed. Every state
-- that may reach VERIFIED/UNABLE_TO_VERIFY may now also reach REGRESSION_DETECTED;
-- all other transitions are unchanged.

DROP TRIGGER IF EXISTS security_remediation_campaign_finding_transition_guard;

CREATE TRIGGER security_remediation_campaign_finding_transition_guard
BEFORE UPDATE OF status ON security_remediation_campaign_findings
WHEN OLD.status <> NEW.status AND NOT (
  (OLD.status = 'QUEUED' AND NEW.status IN (
    'PREPARING_FIX','AWAITING_REVIEW','APPLYING','VALIDATING','RETESTING',
    'VERIFIED','STILL_VULNERABLE','MANUAL_ACTION_REQUIRED','UNABLE_TO_VERIFY',
    'REGRESSION_DETECTED','BLOCKED','SKIPPED'
  )) OR
  (OLD.status = 'PREPARING_FIX' AND NEW.status IN (
    'AWAITING_REVIEW','APPLYING','VALIDATING','RETESTING','VERIFIED',
    'STILL_VULNERABLE','MANUAL_ACTION_REQUIRED','UNABLE_TO_VERIFY',
    'REGRESSION_DETECTED','BLOCKED','SKIPPED','QUEUED'
  )) OR
  (OLD.status = 'AWAITING_REVIEW' AND NEW.status IN (
    'APPLYING','VALIDATING','RETESTING','VERIFIED','STILL_VULNERABLE',
    'UNABLE_TO_VERIFY','REGRESSION_DETECTED','BLOCKED','SKIPPED','QUEUED'
  )) OR
  (OLD.status = 'APPLYING' AND NEW.status IN (
    'VALIDATING','RETESTING','VERIFIED','STILL_VULNERABLE','UNABLE_TO_VERIFY',
    'REGRESSION_DETECTED','BLOCKED','QUEUED'
  )) OR
  (OLD.status = 'VALIDATING' AND NEW.status IN (
    'RETESTING','VERIFIED','STILL_VULNERABLE','UNABLE_TO_VERIFY',
    'REGRESSION_DETECTED','BLOCKED','QUEUED'
  )) OR
  (OLD.status = 'RETESTING' AND NEW.status IN (
    'VERIFIED','STILL_VULNERABLE','UNABLE_TO_VERIFY','REGRESSION_DETECTED',
    'BLOCKED','QUEUED'
  )) OR
  (OLD.status = 'STILL_VULNERABLE' AND NEW.status IN (
    'PREPARING_FIX','AWAITING_REVIEW','RETESTING','VERIFIED',
    'UNABLE_TO_VERIFY','REGRESSION_DETECTED','BLOCKED','SKIPPED','QUEUED'
  )) OR
  (OLD.status = 'UNABLE_TO_VERIFY' AND NEW.status IN (
    'PREPARING_FIX','AWAITING_REVIEW','RETESTING','VERIFIED',
    'STILL_VULNERABLE','REGRESSION_DETECTED','BLOCKED','SKIPPED','QUEUED'
  )) OR
  (OLD.status = 'REGRESSION_DETECTED' AND NEW.status IN (
    'BLOCKED','QUEUED','PREPARING_FIX','AWAITING_REVIEW','SKIPPED'
  )) OR
  (OLD.status = 'BLOCKED' AND NEW.status IN (
    'QUEUED','PREPARING_FIX','AWAITING_REVIEW','APPLYING','VALIDATING',
    'RETESTING','VERIFIED','STILL_VULNERABLE','UNABLE_TO_VERIFY',
    'REGRESSION_DETECTED','MANUAL_ACTION_REQUIRED','SKIPPED'
  )) OR
  (OLD.status = 'MANUAL_ACTION_REQUIRED' AND NEW.status IN (
    'QUEUED','RETESTING','VERIFIED','STILL_VULNERABLE','UNABLE_TO_VERIFY',
    'REGRESSION_DETECTED','BLOCKED','SKIPPED'
  )) OR
  (OLD.status = 'VERIFIED' AND NEW.status = 'QUEUED') OR
  (OLD.status = 'SKIPPED' AND NEW.status = 'QUEUED')
)
BEGIN
  SELECT RAISE(ABORT, 'invalid remediation campaign finding transition');
END;
